### ISSUE TITLE
CMake & github_actions support [incubator branch request]

### ISSUE THREAD

**Issue by p5-vbnekit** [jkivilin/metamod-p#38]
May you open `cmake` branch here?

I would like to help you with this. I already have [some implementation](https://github.com/p5-vbnekit/metamod-p.forks) on this topic (they have been waiting for their moment for a couple of years).
I would like to try to make several PRs - I would like to do it in stages, split into several working commits. At the end of the path there should be `cmake`, `-Werror -Wall -Weffc++ -Wextra -Wpedantic` and `github actions`.

_Originally posted by @p5-vbnekit in https://github.com/Bots-United/metamod-p/issues/37#issuecomment-2988602249_

**Comment by p5-vbnekit** [comment]
Rebased in [new cmake-2025.06.19 branch](https://github.com/p5-vbnekit/metamod-p.forks/tree/cmake-2025.06.19) in my fork.

There are lot of compiler warnings. =)
`-Wall -Weffc++ -Wextra -Wpedantic` on my compiler produces 2220 total warnings.
But i have fixes already too. If you preaprove this, i can cherry-pick all.

**Comment by tschumann** [comment]
Go ahead and make the branches/pull requests - tag @TheStormN when ready.

With regards to 64-bit, I think it's good to add - apparently Sven Coop 6.0 is getting 64-bit support: https://vghe.net/sven-coop.html / https://vghe.net/goldsource-engine.html#64-bit-support so it would be good to be able to support that.

**Comment by p5-vbnekit** [comment]
Automatic release assets (via [softprops/action-gh-release](https://github.com/softprops/action-gh-release)) generation fixed and works now:

```yaml
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [ packages ]
    runs-on: ubuntu-latest
    steps:
      - id: cache
        uses: actions/cache/restore@v4
        with:
          key: packages/${{ github.run_id }}
          path: cache/packages
      - if: steps.cache.outputs.cache-hit != 'true'
        name: Abort on cache not found
        shell: python3 {0}
        run: raise FileNotFoundError("cache/packages")
      - name: Generating release assets
        run: |
          # generating release assets
          mkdir release_assets
          cp cache/packages/podman/debian/buster/i686-linux-gnu.tar.xz release_assets/
          cp cache/packages/podman/debian/buster/x86_64-linux-gnu.tar.xz release_assets/
          cp cache/packages/podman/debian/buster/i686-w64-mingw32-win32.zip release_assets/
          cp cache/packages/podman/debian/buster/x86_64-w64-mingw32-win32.zip release_assets/
          cp cache/packages/msvc/x86.zip release_assets/i686-msvc.zip
          cp cache/packages/msvc/x64.zip release_assets/x86_64-msvc.zip
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: release_assets/*
```

![Image](https://github.com/user-attachments/assets/68214911-7b22-4df4-9145-c3d4c132a2e6)
